// Generated by https://quicktype.io

export interface EmpModel {
  EmpId: string;
  EmpName: string;
  IsReviewer: string;
  IsApprover: string;
  IsCompleted: string;
  LoanLimit: number;
}

export class EmpDataClass {
  mockData: EmpModel[];

  constructor() {
    this.mockData = [
      {
        EmpId: "10",
        EmpName: "shobhit",
        IsReviewer: "Y",
        IsApprover: "N",
        IsCompleted: "N",
        LoanLimit: 1200
      },
      {
        EmpId: "101",
        EmpName: "GF of shobhit",
        IsReviewer: "Y",
        IsApprover: "N",
        IsCompleted: "y",
        LoanLimit: 1100
      },
      {
        EmpId: "11",
        EmpName: "Deepak",
        IsReviewer: "Y",
        IsApprover: "y",
        IsCompleted: "N",
        LoanLimit: 5600
      },
      {
        EmpId: "110",
        EmpName: "wife of Deepak",
        IsReviewer: "Y",
        IsApprover: "N",
        IsCompleted: "N",
        LoanLimit: 5500
      },
      {
        EmpId: "22",
        EmpName: "Rajiv",
        IsReviewer: "Y",
        IsApprover: "Y",
        IsCompleted: "",
        LoanLimit: 8500
      },
      {
        EmpId: "220",
        EmpName: "wife of Rajiv",
        IsReviewer: "Y",
        IsApprover: "Y",
        IsCompleted: "y",
        LoanLimit: 8200
      },
      {
        EmpId: "11",
        EmpName: "kIRAN",
        IsReviewer: "N",
        IsApprover: "Y",
        IsCompleted: "N",
        LoanLimit: 9900
      },
      {
        EmpId: "n1661",
        EmpName: "Kapil",
        IsReviewer: "N",
        IsApprover: "n",
        IsCompleted: "N",
        LoanLimit: 9500
      }
    ];
  }
}
